version: '3.8'
services:
  djangopdf:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - rabbitmq
    command: >
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
  
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 15672:15672
    expose:
      - 15672


  celery:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - djangopdf
      - rabbitmq
    depends_on:
      - rabbitmq
    command: celery -A celeryproj worker -l info
